### ISSUE TITLE
uninitialized constant

### ISSUE THREAD

**Issue by cmunozgar** [krhorst/active_admin_importable#10] opened 2013-04-16 21:05 UTC
Hi, I'm trying to import a csv from a model called 'SpotStatus' and I'm getting the current error:  NameError (uninitialized constant SpotStatu)

Any chance there's a fix to this?

**Comment by antonzaytsev** [comment] 2013-04-17 01:42
Hi cmunozgar,

looks like you did a mistake somewhere,
can you please show here your code of active admin controller where you turned on active_admin_importable?

**Comment by Blue-Dog-Archolite** [comment] 2013-04-17 01:55
I would be money that the issue is that SpotStatus has issues with pluralization.

```
1.9.3p194 :003 > "SpotStatus".singularize
=> "SpotStatu"
1.9.3p194 :006 > "SpotStatus".pluralize
=> "SpotStatuses"
```

Just a thought.

**Comment by cmunozgar** [comment] 2013-04-17 15:31
Hi,

Here is my code:

ActiveAdmin.register SpotStatus do
  active_admin_importable
  menu :parent => "Spots"
end

I'm with  Blue-Dog-Archolite that it can be a thing with the pluralization because other Models have worked correctly!

**Comment by krhorst** [comment] 2013-04-17 16:26
Just pushed a fix to this.

Added a call to pluralize before constantize to get around the "singularizing the singular" troubles with irregular plurals (https://github.com/rails/rails/pull/8671).

**Closed as completed by krhorst** 2013-04-17 16:26 UTC
